services:
  mysqldb:
    image: mysql:9.0.1
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: mysql $MYSQLDB_DATABASE --user=root --password='$MYSQLDB_ROOT_PASSWORD' --silent --execute "SELECT 1;"
      interval: 5s
      timeout: 5s
      retries: 3
  fasms:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - HOST=mysqldb
      - USER=$MYSQLDB_USER
      - PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB=$MYSQLDB_DATABASE
      - POST=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
